apiVersion: apps/v1
kind: Deployment
metadata:
  name: aixa-deployment
  namespace: aixa-namespace
  labels:
    app: student-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
        - name: student-service
          image: aixa949/hf-232-01-aixa-gonzales:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8093
          env:
            - name: SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: aixa-secret
                  key: app-port
            - name: SPRING_PROFILES_ACTIVE
              value: dev
